create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'viewer' check (role in ('admin', 'agent', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visitors (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  email text,
  phone text,
  current_url text,
  current_path text,
  page_title text,
  referrer text,
  timezone text,
  locale text,
  last_user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.visitors
  add column if not exists phone text;

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null references public.visitors (id) on delete cascade,
  status text not null default 'open' check (status in ('open', 'pending', 'closed')),
  assigned_admin_id uuid references public.profiles (id) on delete set null,
  last_message_at timestamptz not null default now(),
  last_message_preview text,
  unread_by_admin integer not null default 0,
  unread_by_visitor integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_id uuid references auth.users (id) on delete set null,
  sender_type text not null check (sender_type in ('visitor', 'admin', 'system')),
  body text not null check (char_length(trim(body)) > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.visitors (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  event_type text not null,
  pathname text,
  current_url text,
  page_title text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.widget_settings (
  id text primary key default 'default',
  position text not null default 'right' check (position in ('left', 'right')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.widget_settings (id, position)
values ('default', 'right')
on conflict (id) do nothing;

create index if not exists conversations_visitor_id_idx
  on public.conversations (visitor_id, updated_at desc);

create index if not exists conversations_last_message_at_idx
  on public.conversations (last_message_at desc);

create index if not exists messages_conversation_id_idx
  on public.messages (conversation_id, created_at asc);

create index if not exists visitors_last_seen_at_idx
  on public.visitors (last_seen_at desc);

create index if not exists visitor_events_visitor_id_idx
  on public.visitor_events (visitor_id, created_at desc);

create or replace function public.sync_profile_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is not null then
    insert into public.profiles (id, email, full_name)
    values (
      new.id,
      new.email,
      coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
    )
    on conflict (id) do update
      set email = excluded.email,
          full_name = coalesce(excluded.full_name, public.profiles.full_name),
          updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists sync_profile_from_auth on auth.users;
create trigger sync_profile_from_auth
after insert or update on auth.users
for each row execute function public.sync_profile_from_auth();

create or replace function public.is_dashboard_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'agent')
  );
$$;

create or replace function public.handle_new_message()
returns trigger
language plpgsql
as $$
begin
  update public.conversations
  set last_message_at = new.created_at,
      last_message_preview = left(regexp_replace(new.body, '\s+', ' ', 'g'), 160),
      unread_by_admin = case
        when new.sender_type = 'visitor' then unread_by_admin + 1
        else unread_by_admin
      end,
      unread_by_visitor = case
        when new.sender_type = 'admin' then unread_by_visitor + 1
        else unread_by_visitor
      end,
      status = case
        when new.sender_type = 'visitor' and status = 'closed' then 'open'
        else status
      end,
      assigned_admin_id = case
        when new.sender_type = 'admin' then coalesce(assigned_admin_id, new.sender_id)
        else assigned_admin_id
      end,
      updated_at = now()
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists conversations_touch_updated_at on public.conversations;
create trigger conversations_touch_updated_at
before update on public.conversations
for each row execute function public.touch_updated_at();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists visitors_touch_updated_at on public.visitors;
create trigger visitors_touch_updated_at
before update on public.visitors
for each row execute function public.touch_updated_at();

drop trigger if exists handle_new_message on public.messages;
create trigger handle_new_message
after insert on public.messages
for each row execute function public.handle_new_message();

drop trigger if exists widget_settings_touch_updated_at on public.widget_settings;
create trigger widget_settings_touch_updated_at
before update on public.widget_settings
for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.visitors enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.visitor_events enable row level security;
alter table public.widget_settings enable row level security;

drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_dashboard_user());

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update"
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_dashboard_user())
with check (id = auth.uid() or public.is_dashboard_user());

drop policy if exists "visitors_select" on public.visitors;
create policy "visitors_select"
on public.visitors
for select
to authenticated
using (id = auth.uid() or public.is_dashboard_user());

drop policy if exists "visitors_insert" on public.visitors;
create policy "visitors_insert"
on public.visitors
for insert
to authenticated
with check (id = auth.uid() or public.is_dashboard_user());

drop policy if exists "visitors_update" on public.visitors;
create policy "visitors_update"
on public.visitors
for update
to authenticated
using (id = auth.uid() or public.is_dashboard_user())
with check (id = auth.uid() or public.is_dashboard_user());

drop policy if exists "conversations_select" on public.conversations;
create policy "conversations_select"
on public.conversations
for select
to authenticated
using (visitor_id = auth.uid() or public.is_dashboard_user());

drop policy if exists "conversations_insert" on public.conversations;
create policy "conversations_insert"
on public.conversations
for insert
to authenticated
with check (visitor_id = auth.uid() or public.is_dashboard_user());

drop policy if exists "conversations_update" on public.conversations;
create policy "conversations_update"
on public.conversations
for update
to authenticated
using (visitor_id = auth.uid() or public.is_dashboard_user())
with check (visitor_id = auth.uid() or public.is_dashboard_user());

drop policy if exists "messages_select" on public.messages;
create policy "messages_select"
on public.messages
for select
to authenticated
using (
  public.is_dashboard_user()
  or exists (
    select 1
    from public.conversations
    where public.conversations.id = messages.conversation_id
      and public.conversations.visitor_id = auth.uid()
  )
);

drop policy if exists "messages_insert_visitor" on public.messages;
create policy "messages_insert_visitor"
on public.messages
for insert
to authenticated
with check (
  sender_type = 'visitor'
  and sender_id = auth.uid()
  and exists (
    select 1
    from public.conversations
    where public.conversations.id = messages.conversation_id
      and public.conversations.visitor_id = auth.uid()
  )
);

drop policy if exists "messages_insert_admin" on public.messages;
create policy "messages_insert_admin"
on public.messages
for insert
to authenticated
with check (
  public.is_dashboard_user()
  and sender_type in ('admin', 'system')
  and (sender_id = auth.uid() or sender_id is null)
);

drop policy if exists "visitor_events_select" on public.visitor_events;
create policy "visitor_events_select"
on public.visitor_events
for select
to authenticated
using (visitor_id = auth.uid() or public.is_dashboard_user());

drop policy if exists "visitor_events_insert" on public.visitor_events;
create policy "visitor_events_insert"
on public.visitor_events
for insert
to authenticated
with check (visitor_id = auth.uid() or public.is_dashboard_user());

drop policy if exists "widget_settings_select" on public.widget_settings;
create policy "widget_settings_select"
on public.widget_settings
for select
to authenticated
using (true);

drop policy if exists "widget_settings_insert" on public.widget_settings;
create policy "widget_settings_insert"
on public.widget_settings
for insert
to authenticated
with check (public.is_dashboard_user());

drop policy if exists "widget_settings_update" on public.widget_settings;
create policy "widget_settings_update"
on public.widget_settings
for update
to authenticated
using (public.is_dashboard_user())
with check (public.is_dashboard_user());

grant usage on schema public to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.visitors to authenticated;
grant select, insert, update on public.conversations to authenticated;
grant select, insert on public.messages to authenticated;
grant select, insert on public.visitor_events to authenticated;
grant select, insert, update on public.widget_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_dashboard_user() to authenticated;

alter table public.visitors replica identity full;
alter table public.conversations replica identity full;
alter table public.messages replica identity full;
alter table public.widget_settings replica identity full;

do $$
begin
  begin
    alter publication supabase_realtime add table public.visitors;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.conversations;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.messages;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.widget_settings;
  exception
    when duplicate_object then null;
  end;
end;
$$;
